import type { InfralensResult } from "../types";

/**
 * Realistic fallback records (real infralens `/api/search` shape) used only
 * when the live API is unreachable, so the dashboard is never empty.
 */
export const INFRALENS_SEED: InfralensResult[] = [
  {
    u: "/tender/meeseva-whatsapp-ai-chatbot-706856",
    lv: "State",
    pl: "TS",
    t: "MeeSeva Whatsapp AI Chatbot",
    or: "Government of Telangana » Information Technology and Communications-Electronic Service Delivery",
    dp: "Information Technology and Communications-Electronic Service Delivery",
    dg: "Posts, Telecom & IT",
    st: "Telangana",
    ct: "Hyderabad",
    sc: "IT / Software",
    wk: "Software / Application",
    vn: 8500000,
    vs: "₹50 L+",
    cl: "9 Jul 2026",
    cn: "2026-07-09 17:00",
    stat: "active",
  },
  {
    u: "/tender/rfp-design-development-of-departmental-websites-311614",
    lv: "State",
    pl: "GJ",
    t: "RFP for Appointment of Agency for Design, Development and Comprehensive Annual Maintenance of Various Websites",
    or: "GMDC » IT Department",
    dp: "IT Department",
    dg: "Posts, Telecom & IT",
    st: "Gujarat",
    ct: "Ahmedabad",
    sc: "IT / Software",
    wk: "Website",
    vn: 12000000,
    vs: "₹1 Cr+",
    cl: "18 Jul 2026",
    cn: "2026-07-18 15:00",
    stat: "active",
  },
  {
    u: "/tender/supply-of-ai-ml-video-analytics-platform-281990",
    lv: "State",
    pl: "AP",
    t: "Supply and Implementation of AI/ML Video Analytics Platform with Central Dashboard",
    or: "AP Technology Services » ITE&C",
    dp: "ITE&C",
    dg: "Posts, Telecom & IT",
    st: "Andhra Pradesh",
    ct: "Amaravati",
    sc: "IT / Software",
    wk: "Software / Application",
    vn: 24000000,
    vs: "₹2 Cr+",
    cl: "2 Jul 2026",
    cn: "2026-07-02 14:30",
    stat: "active",
  },
  {
    u: "/tender/mobile-application-for-field-data-automation-149021",
    lv: "Central",
    pl: "CPP",
    t: "Development of Mobile Application for Field Data Collection and Process Automation",
    or: "Ministry of Rural Development",
    dp: "Department of Rural Development",
    dg: "Posts, Telecom & IT",
    st: "Delhi",
    ct: "New Delhi",
    sc: "IT / Software",
    wk: "Software / Application",
    vn: 6500000,
    vs: "₹50 L+",
    cl: "11 Jul 2026",
    cn: "2026-07-11 16:00",
    stat: "active",
  },
  {
    // Pure department-override case: IT department, no keyword in the title.
    u: "/tender/o-and-m-of-state-data-centre-infrastructure-770011",
    lv: "State",
    pl: "KA",
    t: "Operation and Maintenance of State Data Centre Infrastructure",
    or: "Directorate of Information Technology, Government of Karnataka",
    dp: "Directorate of Information Technology",
    dg: "Posts, Telecom & IT",
    st: "Karnataka",
    ct: "Bengaluru",
    sc: "IT / Software",
    wk: "Maintenance / O&M",
    vn: 45000000,
    vs: "₹4 Cr+",
    cl: "15 Jul 2026",
    cn: "2026-07-15 16:00",
    stat: "active",
  },
  {
    u: "/tender/digital-transformation-data-analytics-consulting-518004",
    lv: "State",
    pl: "MH",
    t: "Selection of Consultant for Digital Transformation and Data Analytics Programme",
    or: "Directorate of IT, Government of Maharashtra",
    dp: "Directorate of Information Technology",
    dg: "Posts, Telecom & IT",
    st: "Maharashtra",
    ct: "Mumbai",
    sc: "IT / Software",
    wk: "Consultancy",
    vn: 18000000,
    vs: "₹1 Cr+",
    cl: "21 Jul 2026",
    cn: "2026-07-21 15:30",
    stat: "active",
  },
];
